# generate_cla.py
#
# Generates the 64 flat CLA carry equations for cla64_flat.v.
#
# The generated equations are saved automatically as:
#     cla64_carry_equations.v
#
# in the SAME folder as this Python script.

from pathlib import Path


# ---------------------------------------------------------------
# Output file
# ---------------------------------------------------------------

SCRIPT_DIR = Path(__file__).resolve().parent
OUTPUT_FILE = SCRIPT_DIR / "cla64_carry_equations.v"


# ---------------------------------------------------------------
# Generate one carry equation
# ---------------------------------------------------------------

def generate_carry(k):
    """
    Generate the direct carry equation for c[k].

    General form:

    C[k] = G[k-1]
         + P[k-1]G[k-2]
         + P[k-1]P[k-2]G[k-3]
         + ...
         + P[k-1]...P[0]Cin
    """

    terms = []

    # First term:
    # G[k-1]
    terms.append(f"g[{k - 1}]")

    # Intermediate generate terms:
    #
    # P[k-1] & G[k-2]
    # P[k-1] & P[k-2] & G[k-3]
    # ...
    #
    for j in range(k - 2, -1, -1):

        p_terms = " & ".join(
            f"p[{i}]"
            for i in range(k - 1, j, -1)
        )

        terms.append(
            f"({p_terms} & g[{j}])"
        )

    # Final input-carry term:
    #
    # P[k-1] & P[k-2] & ... & P[0] & cin
    #
    p_terms = " & ".join(
        f"p[{i}]"
        for i in range(k - 1, -1, -1)
    )

    terms.append(
        f"({p_terms} & cin)"
    )

    # Put all terms together using OR (|)
    equation = f"assign #(2) c[{k}] =\n"
    equation += "    " + " |\n    ".join(terms)
    equation += ";"

    return equation


# ---------------------------------------------------------------
# Generate all 64 equations
# ---------------------------------------------------------------

def generate_all_equations():

    output = []

    output.append(
        "// ================================================================"
    )
    output.append(
        "// FLAT CLA CARRY EQUATIONS"
    )
    output.append(
        "// Generated by generate_cla.py"
    )
    output.append(
        "// ================================================================"
    )
    output.append("")

    # Organise the equations into groups of 8
    #
    # c[1]  - c[8]
    # c[9]  - c[16]
    # ...
    # c[57] - c[64]
    #
    for start in range(1, 65, 8):

        end = min(start + 7, 64)

        output.append(
            "// ------------------------------------------------"
        )
        output.append(
            f"// Carry equations: c[{start}] through c[{end}]"
        )
        output.append(
            "// ------------------------------------------------"
        )
        output.append("")

        for k in range(start, end + 1):

            output.append(
                generate_carry(k)
            )

            output.append("")

    output.append(
        "// ================================================================"
    )
    output.append(
        "// END GENERATED CARRY EQUATIONS"
    )
    output.append(
        "// ================================================================"
    )

    return "\n".join(output)


# ---------------------------------------------------------------
# Main program
# ---------------------------------------------------------------

if __name__ == "__main__":

    # Generate all equations
    generated = generate_all_equations()

    # Print them to the terminal
    print(generated)

    # Save them to a Verilog file in the SAME folder
    # as this Python script
    with open(OUTPUT_FILE, "w") as f:
        f.write(generated)

    print()
    print("================================================")
    print("Generated Verilog file:")
    print(OUTPUT_FILE)
    print("================================================")